
<?php $__env->startSection('title', 'Student Profiles'); ?>
<?php $__env->startSection('page_title', 'Student Profiles'); ?>
<?php $__env->startSection('subtitle', 'Review personal, educational, employment, and guardian information for every learner.'); ?>
<?php $__env->startSection('content'); ?>
<div class="admin-card" style="overflow:hidden;">
  <div style="display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap;margin-bottom:1rem;"><div><h3 style="margin:0;">Learner profiles</h3><p style="margin:.3rem 0 0;color:var(--text-muted);"><?php echo e($students->total()); ?> registered learners</p></div><a class="btn" style="width:auto;" href="<?php echo e(route('sias.admin.students.create')); ?>">Register learner</a></div>
  <div style="overflow-x:auto;"><table style="width:100%;min-width:760px;border-collapse:collapse;"><thead><tr style="text-align:left;color:var(--text-muted);font-size:.75rem;text-transform:uppercase;border-bottom:1px solid var(--card-border);"><th style="padding:.75rem;">Learner</th><th style="padding:.75rem;">Birthdate / Sex</th><th style="padding:.75rem;">Education</th><th style="padding:.75rem;">Employment</th><th style="padding:.75rem;">Action</th></tr></thead><tbody><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $students; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $student): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><?php ($data = $student->settings['registration'] ?? []); ?><tr style="border-bottom:1px solid var(--card-border);"><td style="padding:.75rem;"><strong><?php echo e($student->name); ?></strong><small style="display:block;color:var(--text-muted);"><?php echo e($student->lrn ?? $student->id); ?></small></td><td style="padding:.75rem;"><?php echo e($data['birthdate'] ?? '—'); ?><small style="display:block;color:var(--text-muted);"><?php echo e($data['sex'] ?? '—'); ?></small></td><td style="padding:.75rem;"><?php echo e($data['educational_attainment'] ?? '—'); ?><small style="display:block;color:var(--text-muted);"><?php echo e($data['school'] ?? '—'); ?></small></td><td style="padding:.75rem;"><?php echo e($data['employment_status'] ?? '—'); ?><small style="display:block;color:var(--text-muted);"><?php echo e($data['occupation'] ?? '—'); ?></small></td><td style="padding:.75rem;"><a href="<?php echo e(route('sias.admin.students.show', $student->id)); ?>" style="color:var(--accent);">View</a></td></tr><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></tbody></table></div>
  <div style="margin-top:1rem;"><?php echo e($students->links()); ?></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('sias.admin.layouts.master', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\skillupv2\resources\views\sias\admin\students\profiles\index.blade.php ENDPATH**/ ?>